languageCode: vi-vn
copyright: This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License.
title: The Vietnamese Christian Hymnal
description: The Vietnamese Christian Hymnal
baseURL: https://hymnal.thien.dev/
theme: hymn
paginate: 40
outputs:
  home:
  - HTML
  - RSS
  - Algolia
taxonomies:
  categories: categories
params:
  description: The Vietnamese Christian Hymnal
  favicon: img/icon/favicon.png
  images:
    - img/index.png
  algolia:
    vars: ["title", "content", "summary", "date", "publishdate", "permalink"]
    params: ["categories"]

outputFormats:
  Algolia:
    baseName: algolia
    isPlainText: true
    mediaType: application/json
    notAlternative: true
markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
menu:
  main:
  - identifier: about
    title: About
    url: /pages/about
  footer:
    - identifier: 1
      title: RSS
      url: /index.xml
